shapenet_root: ../ShapeNetCore.v2
gpu_numbers: [0]
use_cuda: True
test_mode: False
resume_training: True
use_scheduler: True
defaults:
    - experiment: regular_cnn_ho3d
hydra:
    run:
        dir: outputs/${experiment.name}/lr:${experiment.fast_lr}_batchsz:${experiment.batch_size}
