shapenet_root: ../ShapeNetCore.v2
gpu_numbers: [0]
use_cuda: True
test_mode: False
resume_training: True
resume_scheduler: True
defaults:
    - experiment: maml_resnet_obman
hydra:
    run:
        dir: outputs/${experiment.name}/lr:${experiment.fast_lr}_batchsz:${experiment.batch_size}
